"""Audit customer_2000 dataset.

Engineering-grade and human-grade checks. Writes findings to
`data/AUDIT_REPORT.md`. Idempotent — run any time.

Usage:
    python scripts/audit_data.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "customer_2000"
REPORT = ROOT / "data" / "AUDIT_REPORT.md"

TABLES = [
    "customers",
    "customer_bridge",
    "customer_contacts",
    "customer_adjustments",
    "customer_email_logs",
    "customer_notes",
    "customer_review_logs",
    "customer_support_bridge",
    "engagement_events",
    "fulfillment_events",
    "order_lines",
    "orders",
    "review_outcomes",
    "support_tickets",
]


def load(name: str) -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / f"{name}.csv", low_memory=False)


def section(lines: list[str], title: str) -> None:
    lines.append(f"\n## {title}\n")


def main() -> int:
    if not DATA_DIR.exists():
        print(f"Missing {DATA_DIR}", file=sys.stderr)
        return 1

    frames: dict[str, pd.DataFrame] = {t: load(t) for t in TABLES}
    out: list[str] = []
    out.append("# customer_2000 Audit Report\n")
    out.append(f"_Generated by `scripts/audit_data.py`. Tables scanned: {len(TABLES)}._\n")

    # ---------- 1. Inventory ----------
    section(out, "1. Inventory")
    out.append("| Table | Rows | Columns | Synthetic % |")
    out.append("|---|---:|---:|---:|")
    for name, df in frames.items():
        syn = ""
        if "synthetic_flag" in df.columns:
            true_rate = (df["synthetic_flag"].astype(str).str.lower() == "true").mean()
            syn = f"{true_rate:.0%}"
        out.append(f"| {name} | {len(df):,} | {len(df.columns)} | {syn} |")

    # ---------- 2. Customer ID coverage ----------
    section(out, "2. Customer ID coverage (FK integrity)")
    cust_ids = set(frames["customers"]["customer_id"])
    out.append(f"`customers.csv` defines **{len(cust_ids):,}** unique customer IDs.\n")
    out.append("| Child table | Has customer_id | Unknown IDs | Customers covered |")
    out.append("|---|---:|---:|---:|")
    for name, df in frames.items():
        if name == "customers" or "customer_id" not in df.columns:
            continue
        child = set(df["customer_id"].dropna())
        unknown = child - cust_ids
        coverage = len(child & cust_ids)
        out.append(
            f"| {name} | {len(child):,} | {len(unknown):,} | {coverage:,} ({coverage/len(cust_ids):.0%}) |"
        )

    # ---------- 3. Date sanity ----------
    section(out, "3. Date sanity")
    out.append("Looking for forward-dated rows, null dates, and impossible ranges.\n")
    today = pd.Timestamp("2026-05-09")
    date_cols = {
        "customers": ["customer_since"] if "customer_since" in frames["customers"].columns else [],
        "orders": ["order_date", "shipping_date"],
        "support_tickets": ["date_of_purchase", "first_response_time", "time_to_resolution"],
        "customer_notes": ["note_date"],
        "customer_email_logs": ["date"],
        "customer_review_logs": ["reviewed_at"],
        "review_outcomes": ["outcome_date"],
        "engagement_events": ["event_date"],
        "fulfillment_events": ["event_date"],
        "customer_adjustments": ["created_date"],
    }
    out.append("| Table | Column | Min | Max | Future rows | Null rows |")
    out.append("|---|---|---|---|---:|---:|")
    for table, cols in date_cols.items():
        df = frames.get(table)
        if df is None:
            continue
        for col in cols:
            if col not in df.columns:
                continue
            parsed = pd.to_datetime(df[col], errors="coerce")
            future = (parsed > today).sum()
            nulls = parsed.isna().sum()
            mn = parsed.min()
            mx = parsed.max()
            out.append(
                f"| {table} | {col} | {mn} | {mx} | {future:,} | {nulls:,} |"
            )

    # ---------- 4. Duplicates ----------
    section(out, "4. Duplicate primary keys")
    pk_map = {
        "customers": "customer_id",
        "orders": "order_id",
        "order_lines": "order_line_id",
        "support_tickets": "ticket_id",
        "customer_notes": "note_id",
        "customer_email_logs": "email_id",
        "customer_review_logs": "review_id",
        "review_outcomes": "outcome_id",
        "engagement_events": "engagement_id",
        "fulfillment_events": "fulfillment_event_id",
        "customer_contacts": "contact_id",
        "customer_adjustments": "adjustment_id",
    }
    out.append("| Table | PK | Duplicates |")
    out.append("|---|---|---:|")
    for table, pk in pk_map.items():
        df = frames.get(table)
        if df is None or pk not in df.columns:
            continue
        dups = df[pk].duplicated().sum()
        out.append(f"| {table} | {pk} | {dups:,} |")

    # ---------- 5. Scenario / topic distribution ----------
    section(out, "5. Scenario & topic distribution")
    for table in ["customer_notes", "customer_email_logs", "customer_review_logs"]:
        df = frames.get(table)
        if df is None or "scenario" not in df.columns:
            continue
        out.append(f"\n**{table}.scenario** — top values:")
        out.append("```")
        out.append(df["scenario"].value_counts().head(10).to_string())
        out.append("```")

    # ---------- 6. source_signal_ids resolvability ----------
    section(out, "6. source_signal_ids resolvability")
    out.append(
        "Notes and emails reference upstream evidence via `source_signal_ids`. "
        "Checking whether those IDs resolve to real ticket/order rows.\n"
    )
    ticket_ids = set(frames["support_tickets"]["ticket_id"].dropna())
    order_ids = set(frames["orders"]["order_id"].dropna())
    known = ticket_ids | order_ids
    for table in ["customer_notes", "customer_email_logs"]:
        df = frames[table]
        col = "source_signal_ids"
        if col not in df.columns:
            continue
        non_null = df[col].dropna().astype(str)
        non_empty = non_null[non_null.str.strip() != ""]
        all_refs = []
        for cell in non_empty:
            for ref in cell.replace(" ", "").split(";"):
                if ref:
                    all_refs.append(ref)
        resolved = sum(1 for r in all_refs if r in known)
        out.append(
            f"- **{table}**: {len(non_empty):,}/{len(df):,} rows carry refs. "
            f"{len(all_refs):,} refs total, {resolved:,} resolve "
            f"({resolved/max(len(all_refs),1):.0%})."
        )

    # ---------- 7. Lifecycle stage gap ----------
    section(out, "7. Lifecycle stage")
    cust = frames["customers"]
    has_stage = "lifecycle_stage" in cust.columns
    out.append(
        f"`customers.lifecycle_stage` present: **{has_stage}**. "
        "If absent, build script will synthesize from order recency, ticket state, and engagement.\n"
    )

    # ---------- 8. Tenant column gap ----------
    section(out, "8. Tenant column")
    has_tenant = any("tenant_id" in df.columns for df in frames.values())
    out.append(
        f"Any table carrying `tenant_id`: **{has_tenant}**. "
        "Build script will inject `tenant_id` on every table for multi-tenant isolation.\n"
    )

    # ---------- 9. Human-readable smell test ----------
    section(out, "9. Human smell test (sample 3 customers)")
    sample = cust.sample(min(3, len(cust)), random_state=42)
    for _, row in sample.iterrows():
        cid = row["customer_id"]
        name = row.get("customer_full_name", "?")
        out.append(f"\n### {name} ({cid})")
        seg = row.get("customer_segment", "?")
        rev = row.get("total_sales", "?")
        late = row.get("late_delivery_rate", "?")
        out.append(f"- Segment: {seg} · Total sales: {rev} · Late delivery rate: {late}")
        for tbl in ["orders", "support_tickets", "customer_notes", "customer_email_logs"]:
            df = frames[tbl]
            if "customer_id" in df.columns:
                n = (df["customer_id"] == cid).sum()
                out.append(f"- {tbl}: {n} rows")

    # ---------- 10. Column inventory per table ----------
    section(out, "10. Column inventory")
    for name, df in frames.items():
        out.append(f"\n**{name}** ({len(df.columns)} cols): `{', '.join(df.columns)}`")

    REPORT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
